"""
Django settings for travnik project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import socket

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's#i56(1zz%a=y3%j!&edgohhav0kp^tu_l1+qlh8v)e&snyei)'

# SECURITY WARNING: don't run with debug turned on in production!
try:
    HOSTNAME = socket.gethostname()
except:
    HOSTNAME = 'localhost'

if HOSTNAME in ['ubuntu']:
    DEBUG = True
    COMPRESS_ENABLED = False
    HTML_MINIFY = True
    CACHE_ENABLED = False
    DEBUG_TOOLBAR = False
else:
    DEBUG = False
    DEBUG_TOOLBAR = False
    CACHE_ENABLED = True
    COMPRESS_ENABLED = True
    HTML_MINIFY = True


ALLOWED_HOSTS = ['127.0.0.1', 'medavi.ru']




# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'super_model',
    'helper',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.vk',
    'allauth.socialaccount.providers.openid',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'sorl.thumbnail',
    'django.contrib.redirects',
    'compressor',
    'reversion',
    'ckeditor',
    'ckeditor_uploader',
    'mptt',
    'django_mobile',
    'haystack',
    'contact_form',
    'main',
)




MIDDLEWARE_CLASSES = (
    'django.middleware.http.ConditionalGetMiddleware',
    'django_mobile.middleware.MobileDetectionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'reversion.middleware.RevisionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'super_model.middleware.SetClientIpMiddleware',
    'super_model.middleware.SetUserKeyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    #'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
    'main.middleware.PlantSynonymsFallbackMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
)

ROOT_URLCONF = 'travnik.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'main/templates/main')],
        #'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'super_model.context_processors.debug',
                'super_model.context_processors.show_ad',
                'super_model.context_processors.base_template',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_mobile.context_processors.flavour',

            ],
        },
    },
]

WSGI_APPLICATION = 'travnik.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'travnik',
        'USER': 'kulik',
        'PASSWORD': 'ZaX369Exn',
       'HOST': '127.0.0.1',
       'PORT': '5432',
        'CONN_MAX_AGE': 500,
        },


}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


SITE_ID = '1'
SITE_URL = 'http://medavi.ru'
DEFAULT_FROM_EMAIL = 'Medavi.ru <info@medavi.ru>'
SERVER_EMAIL = 'info@medavi.ru'
INTERNAL_IPS = ['127.0.0.1']
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'  # URL для медии в шаблонах
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
#SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_CACHE_ALIAS = "default"
SESSION_SAVE_EVERY_REQUEST = False
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True


#**************<<<<<
POST_COMMENTS_PAGE_SIZE = 30
POST_LIST_PAGE_SIZE = 48

APPEND_SLASH = True


#allauth
LOGIN_REDIRECT_URLNAME = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_MIN_LENGTH = 5
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 30
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_PASSWORD_MIN_LENGTH = 6
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False
ACCOUNT_USERNAME_REQUIRED = True
SOCIALACCOUNT_ADAPTER  = "super_model.adapter.SuperSocialAccountAdapter"
ACCOUNT_ADAPTER = "super_model.adapter.SuperAccountAdapter"


AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)


CACHES = {
    "default": {
        'BACKEND': 'redis_cache.RedisCache',
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            'DB': 1,
            'PARSER_CLASS': 'redis.connection.HiredisParser',
        }
    }
}


THUMBNAIL_BACKEND = 'super_model.backends.SEOThumbnailBackend'
THUMBNAIL_PREFIX = 'images/'
THUMBNAIL_KVSTORE = 'sorl.thumbnail.kvstores.redis_kvstore.KVStore'
THUMBNAIL_REDIS_DB = 2


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

BEST_COMMENTS_DAYS = 100

CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"


if DEBUG_TOOLBAR:

    MIDDLEWARE_CLASSES = list(MIDDLEWARE_CLASSES)
    MIDDLEWARE_CLASSES.remove('django.middleware.gzip.GZipMiddleware')
    MIDDLEWARE_CLASSES = tuple(MIDDLEWARE_CLASSES)
    INSTALLED_APPS += ('debug_toolbar',)

    DEBUG_TOOLBAR_PATCH_SETTINGS = True
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
    ]



    MIDDLEWARE_CLASSES = ('debug_toolbar.middleware.DebugToolbarMiddleware',) + MIDDLEWARE_CLASSES

    DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,
    }

if CACHE_ENABLED and not DEBUG:

    TEMPLATES[0]['OPTIONS']['loaders'] = [
            #'django_mobile.loader.Loader',
            ('django.template.loaders.cached.Loader',
                  [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
            ],
                ),
        ]
else:
       TEMPLATES[0]['OPTIONS']['loaders'] = [
                    #'django_mobile.loader.Loader',
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
        ]





AUTO_APPROVE_EMAILS = ['approve@approve.me']
AUTO_DONT_APPROVE_EMAILS = ['dont-approve@dont-approve.me']

ADMINS = (('Alex Poleha', 'admin@medavi.ru'),)

PUBLISH_COMMENT_WITHOUT_APPROVE_KARM = 20


HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
    },
}


DEFAULT_THUMBNAIL_QUALITY = 75



CACHED_METHOD_SPECIAL_CASES = {
    'django.core.handlers.wsgi.WSGIRequest': ('user.pk', 'session.user_key', 'client_ip')
}

CACHED_VIEW_DURATION = 60 * 60 * 24 * 7
CACHED_PROPERTY_DURATION = 60 * 60 * 24 * 7
CACHED_METHOD_DURATION = 60 * 60
HISTORY_EXISTS_DURATION = 60 * 60 * 24 * 7
HISTORY_EXISTS_BY_COMMENT_DURATION = 60 * 60 * 24
HISTORY_FULL_EXISTS_BY_COMMENT_DURATION = None

BASE_POST_CLASS = 'main.models.Post'
BASE_HISTORY_CLASS = 'main.models.History'
BASE_MAIL_CLASS = 'main.models.Mail'
BASE_USER_PROFILE_CLASS = 'main.models.UserProfile'
BASE_COMMENT_CLASS = 'main.models.Comment'


SITE_NAME = 'Medavi.ru'



POST_TYPE_PLANT = 1
POST_TYPE_RECIPE = 2
POST_TYPE_USAGE_AREA = 3


POST_TYPES = (
    (POST_TYPE_PLANT, 'Растение'),
    (POST_TYPE_RECIPE, 'Рецепт'),
    (POST_TYPE_USAGE_AREA, 'Область применения'),

)

#SUPER_MODEL_KEY_NAME = 'prozdo_key'


USER_ROLE_REGULAR = 1
USER_ROLE_AUTHOR = 2
USER_ROLE_DOCTOR = 3
USER_ROLE_ADMIN = 33

USER_ROLES = (
        (USER_ROLE_REGULAR, 'Обычный пользователь'),
        (USER_ROLE_AUTHOR, 'Автор'),
        (USER_ROLE_DOCTOR, 'Врач'),
        (USER_ROLE_ADMIN, 'Админ'),
    )

BASE_TEMPLATE = 'main/base/base.html'

EMAIL_IS_REQUIRED_FOR_COMMENT = False


HISTORY_TYPE_COMMENT_CREATED = 1
HISTORY_TYPE_COMMENT_SAVED = 2
HISTORY_TYPE_COMMENT_RATED = 3
HISTORY_TYPE_POST_CREATED = 4
HISTORY_TYPE_POST_SAVED = 5
HISTORY_TYPE_POST_RATED = 6
HISTORY_TYPE_COMMENT_COMPLAINT = 7

HISTORY_TYPES = (
    (HISTORY_TYPE_COMMENT_CREATED, 'Комментарий создан'),
    (HISTORY_TYPE_COMMENT_SAVED, 'Комментарий сохранен'),
    (HISTORY_TYPE_COMMENT_RATED, 'Комментарий оценен'),
    (HISTORY_TYPE_POST_CREATED, 'Материал создан'),
    (HISTORY_TYPE_POST_SAVED, 'Материал сохранен'),
    (HISTORY_TYPE_POST_RATED, 'Материал оценен'),
    (HISTORY_TYPE_COMMENT_COMPLAINT, 'Жалоба на комментарий'),

)

HISTORY_TYPES_POINTS = {
    HISTORY_TYPE_COMMENT_CREATED: 3,
    HISTORY_TYPE_COMMENT_SAVED: 0,
    HISTORY_TYPE_COMMENT_RATED: 1,
    HISTORY_TYPE_POST_CREATED: 5,
    HISTORY_TYPE_POST_SAVED: 0,
    HISTORY_TYPE_POST_RATED: 1,
    HISTORY_TYPE_COMMENT_COMPLAINT: 0,
    }


#***************
EXCLUDE_FROM_MINIFYING = ('^admin/',)


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        #'height': 300,
        #'width': 300,
    },
    'basic': {
        'toolbar': 'Basic',
        'height': 200,

    },
}