# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagearea',
            name='code',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
