# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160202_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
    ]
