# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160218_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='wikipedia_link',
            field=models.TextField(blank=True, verbose_name='Страница на wikipedia'),
        ),
    ]
