# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_plant_wikipedia_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synonym',
            options={'ordering': ('synonym',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Название'),
        ),
    ]
