# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160302_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='alias',
            field=models.CharField(blank=True, db_index=True, max_length=800, verbose_name='Синоним'),
        ),
    ]
