# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_synonym_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='short_body',
        ),
    ]
