# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 09:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Рецепт'),
        ),
    ]
