# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 12:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160312_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Рецепт'),
        ),
    ]
