# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160312_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='session_key',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_type',
            field=models.IntegerField(choices=[(1, 'Комментарий создан'), (2, 'Комментарий сохранен'), (3, 'Комментарий оценен'), (4, 'Материал создан'), (5, 'Материал сохранен'), (6, 'Материал оценен'), (7, 'Жалоба на комментарий'), (8, 'Пользовательский материал оценен'), (9, 'Жалоба на пользовательский материал')], db_index=True),
        ),
    ]
